import React from 'react'
import Navbar from './components/navbar.js'
import Footer from './components/Foot.js'
import Head from 'next/head'



function aboutMe() {
  return (
    <div className='containerAbout'>
      <Head>
        <title>About Me</title>
        <meta name="aboutMePage" content="Generated by DanielScrypt" />
        <link rel="icon" href="/mill_water_energy_renewable_ecology_icon_191935.ico" />
      </Head>
        <Navbar />
        <div className='contentAbout'>
            <h1 className='title'>
                I'm Daniel !
            </h1>
            <section className='section1'>
               <h2 className='sectionHeader'>
               General Skills
               </h2>
               Self-starter, fast learner, able to quickly adapt to new environments, excellent organizational, 
communication, and interpersonal skills
            </section>
            <section className='section1'>
               <h2 className='sectionHeader'>
               Experience 
               </h2>● An active Scuba Diving Instructor between 07/2019 to 10/2021 (certified as Nitrox, 
Advanced Buoyancy, Navigation, Limited Visibility, Rescue Diver and CPR instructor.) <br/>
● Speedboat operator in a Kitesurfing club (ASA Extreme) <br/>
● Hazmat Specialist on a Drilling Rig (Stena Forth) <br/>
● Professional Yacht Skipper with sailing experience both in Israel and Croatia 

            </section>
            <section className='section1'>
               <h2 className='sectionHeader'>
               Computer Knowledge 

               </h2>● Excellent knowledge in Web Developing both front-end and back-end using HTML, CSS, JS, 
MongoDB, and frameworks such as Express and ReactJS <br/>
● Great understanding and control in office programs such as Excel, Word and PowerPoint
            </section>
            <section className='section1'>
               <h2 className='sectionHeader'>
               Military Service 
               </h2>Israeli Navy – January 2016 through Sep 2018, served on as a combat soldier on a missile 
ship
            </section>
            <section className='section1'> <b>Languages</b>  - Hebrew, English , Italian </section>
        </div>
        <Footer />
    </div>
  )
}

export default aboutMe