import {React, useEffect , useState } from 'react'
import Head from 'next/head'
import Navbar from './components/navbar.js'
import styles from '../styles/Home.module.css'
import FirstContent from './components/FirstContent.js'
import Title from './components/Title.js'
import SecondContent from './components/SecondContent.js'
import Break from './components/Break.js'
import Foot from './components/Foot.js'
import Loading from './components/Loading.js'
import useInView from "react-cool-inview";




export default function Home() {
  const { observe, inView} = useInView();

  const [scrollY, setScrollY] = useState(0);
  const [loading , setLoading] = useState(true)

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    handleScroll();

    setTimeout(() => {
      setLoading(false)
    } , 3000)
    

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };


  }, []);

  const breakHeight = scrollY / 10 > 70 ? '70vh' : `${scrollY / 10}vh`


  return (
    <div className={styles.container}  >
     <Loading  />
      <Head>
        <title>Daniel&apos;s Website</title>
        <meta name="HomePage" content="Generated by DanielScrypt" />
        <link rel="icon" href="/mill_water_energy_renewable_ecology_icon_191935.ico" />
      </Head>
       {!loading && <Navbar colorChange={!inView} />}
      <main className={styles.main} > 
      
        <div className={styles.title} ref={observe}>
          {!loading && <Title />}
        </div>
        <div >
        {!loading && <FirstContent />}
        </div>


          {!loading && <Break 
          scrollY={scrollY} 
          breakHeight={breakHeight} />}


         <div >
        {!loading && <SecondContent />}
        </div>
      </main>

      <footer className={styles.footer}>        
      {!loading && <Foot />}
      </footer>
    </div>
  )
}
