import {React, useEffect , useState } from 'react'
import Head from 'next/head'
import Navbar from './components/navbar.js'
import styles from '../styles/Home.module.css'
import FirstContent from './components/FirstContent.js'
import Title from './components/Title.js'
import SecondContent from './components/SecondContent.js'
import Break from './components/Break.js'
import Foot from './components/Foot.js'
import useInView from "react-cool-inview";



export default function Home() {
  const { observe, inView} = useInView();

  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    handleScroll();

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
    
  }, []);

  const breakHeight = scrollY / 10 > 70 ? '70vh' : `${scrollY / 10}vh`



  return (
    <div className={styles.container}  >
     
      <Head>
        <title>Daniel's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Navbar colorChange={!inView} />
      <main className={styles.main} > 
      
        <div className={styles.title} ref={observe}>
          <Title />
        </div>
        <div >
        <FirstContent />
        </div>


          <Break 
          scrollY={scrollY} 
          breakHeight={breakHeight} />


         <div >
        <SecondContent />
        </div>
      </main>

      <footer className={styles.footer}>        
      <Foot />
      </footer>
    </div>
  )
}
