import React from 'react'
import Navbar from './components/navbar.js'
import Footer from './components/Foot.js'
import Head from 'next/head'

function projects() {
    const projects = [
        {   id:'p1' , 
        projectName: 'Colors Project' , 
        mainImgSrc: 'demo' , 
        imagesSrc : ['demo1' , 'demo2' , 'demo3'], 
        description: 'some some some'
        } , 
        {   id:'p1' , 
        projectName: 'YelpCamp' , 
        mainImgSrc: 'demo' , 
        imagesSrc : ['demo1' , 'demo2' , 'demo3'], 
        description: 'some some some'
        } , 
        {   id:'p1' , 
        projectName: '30 Mini Projects' , 
        mainImgSrc: 'demo' , 
        imagesSrc : ['demo1' , 'demo2' , 'demo3'], 
        description: 'some some some'
        }
    ]
  return (
    <div className='projectPage'>
        <Head>
        <title>My Projects</title>
        <meta name="ProjectsPage" content="Generated by DanielScrypt" />
        <link rel="icon" href="/mill_water_energy_renewable_ecology_icon_191935.ico" />
      </Head>
        <Navbar />
        <div className='projects'>
        <h1 className='title'>Check out some of my skills !</h1>
        {projects.map(p => (
        <section key={p.projectName} className='projectSection'>
            <h2 className='projectHeader'>{p.projectName}</h2>
            <div className='projectContent'>
                <p>{p.description}</p>
                <p>Image goes here</p>
            </div>
        </section>
        ))}
        </div>

        <Footer />
    </div>
  )
}

export default projects